### PR TITLE
Cover GenericExtensions with unit tests and add some checks.

### PR DESCRIPTION
**Pull request by EgorMatirov**
FIXES: #9 
I'm not sure about added checks so if you don't think that they are necessary I have no problem with removing them from PR.

### CODE REVIEW

**Review by Teodor92 — CHANGES_REQUESTED** [review]
Looks awesome! The checks are a nice addition :)

Please do the following naming changes and I'll merge it in.

Use the flowing naming convention for tests:

[MethodName]_[TestSetup]_Should[ExpectedResult]

**Review by Teodor92 — APPROVED** [review]

**Comment by Teodor92** [comment]
Hmm, it's seems there is a conflict in the MoreDotNet.Tests.csproj file (I think I merged another pull request, sorry for that). Could you sync with your fork so I can merge automatically? :)

**Comment by EgorMatirov** [comment]
Yep, no problems. :)

**Comment by Teodor92** [comment]
Merged! Thanks! :)

**Pull request merged**
